#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: c
sudo: false

env:
  BYOND_MAJOR="508"
  BYOND_MINOR="1287"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh

install:
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

script:
  - shopt -s globstar
  - (! grep 'step_[xy]' maps/**/*.dmm)
  - (! find nano/templates/ -type f -exec md5sum {} + | sort | uniq -D -w 32 | grep nano)
  - (num=`grep -E '\\\\(red|blue|green|black|b|i[^mc])' **/*.dm | wc -l`; [ $num -le 1355 ])
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - DreamMaker polaris.dme
